### ISSUE TITLE
Reduce horizontal indent

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-summary#1]
There seems a lot of space between the left edge of the page, and the left edge of the table, e.g. currently visible for http://earthsystemmodeling.org/esmf-test-summary/develop/index.html. It is easy to use the horizontal scroll bar to shift the table, but it would be nice to have less space "waster" by default as the number of columns grows for these tables.

**Comment by rsdunlapiv** [comment]
Try this:
http://earthsystemmodeling.org/esmf-test-summary/develop/index.html

**Comment by theurich** [comment]
This looks really good. Thank you!
