### ISSUE TITLE
Ordering of ESMF hash columns

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-summary#10]
The information we get with `git describe --tags` uses as many digit as it needs to count the number of commits since the last tag. Unfortunately this leads to wrong ordering of the columns when we go from single digit to double digit. e.g. `-9-` will be sorted as later than `-10-, -11-, ...`. Not sure what the solution is, but it would be nice to have columns in the expected way even when we cross into double digit commits since last tag.

**Comment by rsdunlapiv** [comment]
This should be addressed now.
