### ISSUE TITLE
Exclude specific branches from summarization

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-summary#3]
Currently I think **all** of the branches present in any of the artifacts will be considered in the summarizer. In particular it will be used to generate the list of all the combos. Branches can sometimes be pretty unstable - which is the whole reason we test on a branch before merging into develop. This is an important step in the development process, and a huge benefit of the new testing infrastructure to support this! The problem though is that these failures can easily clutter the list of combos, which then is reflected across the summary table of **all** branches. 

I do think it is _correct_ to use the _same_ list of combos for all branch tables! I think the problem can simply be addressed by providing a mechanism to exclude certain branches from summarization once we are done with them. While we are testing the branch, it is okay to have issues like this, but once we are done, we want things to go back to "normal. This will become especially important when these kind of test branches accumulate.

**Comment by rsdunlapiv** [comment]
I see two parts to this:
 - a convenient way to simply ignore ESMF branches in the artifacts (i.e., have the summarizer just "skip over" them)
 - scrubbing the artifacts history for certain ESMF branches entirely, to save space in the artifacts repo

The first one could be done through a configuration option as I suggested in #2.

The second one I think is important, since as @theurich mentioned, most of the value of the ESMF branch is lost after the branch has been merged. In this case, instead of filtering the summarizer, I would like to be able to actually remove the history of the branch testing from the artifacts entirely. 

This latter approach could be accomplished by adopting a new branching strategy for the esmf-test-artifacts.  Namely, we would use the branch pattern `<esmf_branch>/<machine_name>` instead of just `<machine_name>` for the artifacts branches.  For example:

```
develop/cheyenne
develop/discover
develop/hera
myfeature1/cheyenne
myfeature1/discover
myfeature1/hera
myfeature2/cheyenne
```
The `develop/*` branches would be long term branches (since develop is a long term ESMF branch).  The `myfeature1/*` and `myfeature2/*` are feature branches, that after merging into ESMF develop, can be safely deleted within esmf-test-artifacts.  This has the added benefit of helping to control the size of the esmf-test-artifacts, since we'd expect the repo size to be reduced when those artifacts feature branches are deleted.

**Comment by theurich** [comment]
How does the summarizer currently determine the ESMF branches that are captured by the artifacts repo? I thought it is through inspection of the top level directories that exist e.g. under the `<machine_name>` branch. The nice thing is that (I think) it is dynamically picking up any new branches being tested under this machine. 
If we change this to artifacts branches as  `<esmf_branch>/<machine_name>`, I guess the test script has to become smarter, and probably first do a `git branch -a` to determine which branches exist, and go from there. ... Side question, does the summarizer script right now do `git branch -a` to find all the existing `<machine_name>` branches, or are the machine_names accessed from somewhere else? I guess ultimately the `git branch -a` or similar approach is the right one anyway, in order to make this part as dynamic as possible.

So I see that in the dynamic approach with `git branch -a` or similar on the artifacts repo, the suggested `<esmf_branch>/<machine_name>` branching approach allows us to use git level branch removal on the artifacts repo to get rid of it in the summary table. However, it will not shrink the Git artifacts repo, because we are not actually changing the history, just what names are associated with branches in the repo. Not a big deal, but just wanted to point it out.

**Comment by rsdunlapiv** [comment]
> How does the summarizer currently determine the ESMF branches that are captured by the artifacts repo? I thought it is through inspection of the top level directories that exist e.g. under the <machine_name> branch. The nice thing is that (I think) it is dynamically picking up any new branches being tested under this machine.

It uses `git branch -a` to get a list of branches dynamically. Each of those is a machine right now (minus the "main" branch which is ignored.)  Then for each branch, it goes through the commit history in reverse chronological order, looking at the files for each commit (`git show <artifacts_hash> --oneline --name-only`).  The path names in the commit (specifically that of the `summary.dat` file) is used to determine the ESMF branch tested (its the first level folder).


> Side question, does the summarizer script right now do git branch -a to find all the existing <machine_name> branches, or are the machine_names accessed from somewhere else? I guess ultimately the git branch -a or similar approach is the right one anyway, in order to make this part as dynamic as possible.

Right - it's dynamic so any new machine branches are automatically picked up.

> So I see that in the dynamic approach with git branch -a or similar on the artifacts repo, the suggested <esmf_branch>/<machine_name> branching approach allows us to use git level branch removal on the artifacts repo to get rid of it in the summary table. However, it will not shrink the Git artifacts repo, because we are not actually changing the history, just what names are associated with branches in the repo. Not a big deal, but just wanted to point it out.

I'm not sure.  If we create a new `<esmf_branch>/<machine_name>` branch in the esmf-test-artifacts, if the branch is off of the the "main" branch of esmf-test-artifacts, which has only a few initial commits, then I would think it would have its own separate history (unassociated with any other branches). In that case I would think that deleting the branch would be removing history, resulting in a smaller repo.  Maybe I'm not thinking about that right?

**Comment by theurich** [comment]
> > So I see that in the dynamic approach with git branch -a or similar on the artifacts repo, the suggested <esmf_branch>/<machine_name> branching approach allows us to use git level branch removal on the artifacts repo to get rid of it in the summary table. However, it will not shrink the Git artifacts repo, because we are not actually changing the history, just what names are associated with branches in the repo. Not a big deal, but just wanted to point it out.
> 
> I'm not sure. If we create a new `<esmf_branch>/<machine_name>` branch in the esmf-test-artifacts, if the branch is off of the the "main" branch of esmf-test-artifacts, which has only a few initial commits, then I would think it would have its own separate history (unassociated with any other branches). In that case I would think that deleting the branch would be removing history, resulting in a smaller repo. Maybe I'm not thinking about that right?

That's not typically how revision control systems work wrt deleting branches - at least from the general user interface level. There might be admin tools to _really_ delete a branch, but from the user level, doing a `git push origin --delete <branch_name>` really just removes the entry of associating <branch_name> with a specific hash. The hash (and all its predecessors) still exist. It would be horrible if it were different, because there are likely dependencies in the history with different branches... not in the artifacts repo I know, but typically for Git. I use this actually feature sporadically, when I noticed I deleted a branch I did then later needed again.. If I still know the hash, I just check out the hash, and just name it the branch_name again. It's all still there.  (In the old CVS days this was different, but there deleting a branch wasn't even a user level operation... and it was much easier to mess the whole thing up.)

**Comment by rsdunlapiv** [comment]
Huh, I was thinking that there was a way to run the git garbage collector to physically remove that history. After deleting the branch, wouldn't you have a list of dangling commits, that it theory are not accessible, and can therefore be removed?  (Assuming I don't put on any tags, etc.)

**Comment by theurich** [comment]
But wouldn't `git gc`  require some sort of forced push (meaning admin) to GitHub? Maybe that is supported... if so, that definitely would seem to be a good solution here to keep the artifacts repo in check. Not something I would want to do for a source code repo... and I guess that is where I was coming from.
