### ISSUE TITLE
Dropped combo rows on hash specific tables

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-summary#4]
There is a strange issue when following one of the ESMF-hash links at the top of a column in the summary table. E.g. take the current develop table: http://earthsystemmodeling.org/esmf-test-summary/develop/index.html. Notice that all combos 1-94 (right now) do have a row. Also notice that the v8.4.0b08 column has an entry for each row.

Then follow the link for v8.4.0b08 at the top: http://earthsystemmodeling.org/esmf-test-summary/develop/v8.4.0b08.html
This table will list some combos multiple times, which is expected and useful. However not all of the combos shown under the develop summary table are present!!
Examples include (probably incomplete list!) combos: 8, 23, 34, 36, ..., 94. I did hit the "Combo No." sort a few times, just to make sure it wasn't in some other order obscuring the presence, but I am pretty sure those combos are indeed missing.
Also, it does seem to change sometimes what is missing. Yesterday I wrote down that combo 2 was missing in this same table, but today I see that combo. Not sure if that observation is helpful or not.

**Comment by rsdunlapiv** [comment]
@theurich please have another look - I think I was able to resolve this issue with missing rows on the hash-specific tables.

**Comment by theurich** [comment]
That does look good now. Very nice. Thank you!
