### ISSUE TITLE
Color to indicate "Phase: build"

### ISSUE THREAD

**Issue by theurich** [esmf-org/esmf-test-summary#7]
The pop-up info box when hovering over a cell of the summary table (e.g. http://earthsystemmodeling.org/esmf-test-summary/develop/index.html) includes info about "Phase:", which can be "build" or "test".
I think this is super helpful information when trying to understand what is going on. In fact, I think it is so useful that we should highlight cells that  have "Build: PASS", but are still in "Phase: build" in a different color, e.g. orange. I assume that orange cells might still be updated later in the day... but if not, then there is some sort of build issue... which is different than test issues (which are yellow).

**Comment by rsdunlapiv** [comment]
I took an initial pass at this with pending result cells having a fade between blue and white to make it obvious that results are still coming in.
See for example combos 37 and 38 here:
http://earthsystemmodeling.org/esmf-test-summary/patch_8.3.1/index.html

**Comment by theurich** [comment]
Thanks, I think that will work. Personally I prefer a solid color since you can take it in in an instance, while the fading indicator does require you to look a bit, and it plays tricks (with me anyway) when I scroll. But maybe that's just me.

Somewhat related, rows 37 and 38 on http://earthsystemmodeling.org/esmf-test-summary/patch_8.3.1/index.html, seem to be related to 33 and 34. They have the exact same "Clone Time". What made rows 33 and 34 being reported as lib build failures, when now it is looking like the library build actually passed?

**Comment by rsdunlapiv** [comment]
> Somewhat related, rows 37 and 38 on http://earthsystemmodeling.org/esmf-test-summary/patch_8.3.1/index.html, seem to be related to 33 and 34. They have the exact same "Clone Time". What made rows 33 and 34 being reported as lib build failures, when now it is looking like the library build actually passed?

I think what is happening on Cori is that the queue times are extremely long and the job never even runs before the collection script itself times out. The current timeout for the collection script is 24 hours.  When that time is exceeded, the collection script will try to push whatever is there. For example, [this commit](https://github.com/esmf-org/esmf-test-artifacts/tree/efe34129acdda9fa6e43fef9c1e53d2bf592cc65/patch_8.3.1/intel/19.1.2/g/mpi/7.7.19) from Cori does not even have an `out/build.log` file or `out/info.log` file indicating that the build never even started.  

One option we have is to up the timeout to something longer than 24 hours.  We can keep checking indefinitely.  If we do this, then I would change from nightly testing to ever other night.  Probably on Cori, however, we need to figure out if there is a faster queue, or at least understand why the jobs are queued for so long.

**Comment by theurich** [comment]
Two issues discussed here are resolved:

1. Rocky implemented indication of build phase in solid blue color, and it has been working well for a long time.
2. The issue with sometimes Cori stalling I figured out this morning (when it was happening again). The problem is a system issue. They only have a certain number of Intel compiler licenses, and sometimes there seems so much demand on those licenses across the system, that compiler commands "hang". Cori system support is suspecting it also has to do with folks using larger number of parallel builds. Nothing to do from the ESMF side here.
